 --PRACTICAL ASSESSMENT QUESTIONS AND FORMULAS:

 --  1.  Simple Interest: I = P * r * t
 --  2.  Annual Compound: A = P * (1 + r)^n
 --  3.  Hire Purchase Installment: Monthly = [P * (1 + r * t)] / 36
 --  4.  Inflation Projection: A = P * (1 + i)^n
 --  5.  Reducing Balance Depreciation: A = P * (1 - i)^n
 --  6.  Quarterly Compound: A = P * (1 + r/4)^(4 * n)
 --  7.  Monthly Loan Accrual: I = [P * (1 + r/12)^12] - P
 --  8.  Doubling Time (Simple): t = 1 / r
 --  9.  Effective Annual Rate: EAR = (1 + r/m)^m - 1
 --  10. Semi-Annual Growth: A = P * (1 + r/2)^(2 * n)